[theme]
primaryColor = "#4CAF50"  # Keep the primary color as it is
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F0F0"  # Light gray for secondary background
textColor = "#000000"  # Black text
font = "sans serif"
